# Generated by Django 3.1.4 on 2020-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_card', models.CharField(max_length=100)),
                ('hard_drive', models.CharField(max_length=100)),
                ('motherboard', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('shell_color', models.CharField(max_length=100)),
            ],
        ),
    ]
