# Generated by Django 3.1.4 on 2020-12-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
