# Generated by Django 3.1.4 on 2020-12-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_components_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('memory_size', models.IntegerField(default=0)),
                ('Set_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pc')),
            ],
        ),
        migrations.DeleteModel(
            name='Components',
        ),
    ]
