# Generated by Django 3.1.4 on 2020-12-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201219_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video_cards',
        ),
    ]
