# Generated by Django 3.1.4 on 2020-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_video_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_card', models.CharField(max_length=24)),
                ('total_memory', models.IntegerField(default=0)),
            ],
        ),
    ]
