# Generated by Django 3.1.4 on 2020-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_video_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_cards',
            name='Set_number',
            field=models.IntegerField(default=0),
        ),
    ]
