# Generated by Django 3.1.4 on 2020-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_video_cards_set_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_motherboard', models.CharField(max_length=60)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pc',
            name='Total_set_cost',
            field=models.IntegerField(default=0),
        ),
    ]
