# Generated by Django 3.1.4 on 2020-12-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201221_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_cards',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
