# Generated by Django 3.1.4 on 2020-12-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_video_cards_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pc')),
            ],
        ),
    ]
