# Generated by Django 3.1.4 on 2020-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201222_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
