# Generated by Django 3.1.4 on 2021-02-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210202_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(null=True)),
                ('image', models.IntegerField(null=True, verbose_name='Изобржение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('processor', models.CharField(max_length=255, verbose_name='Процессор')),
                ('number_of_cores', models.CharField(max_length=20, verbose_name='Количество ядер')),
                ('video_card', models.CharField(max_length=255, verbose_name='Видео карта')),
                ('video_memory', models.CharField(max_length=20, verbose_name='Видео память')),
                ('ram', models.CharField(max_length=20, verbose_name='Оперативная память')),
                ('disc_type', models.CharField(max_length=20, verbose_name='Тип жесткого диска')),
                ('disc_memory', models.CharField(max_length=20, verbose_name='Общая емкость диска')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardDrives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(null=True)),
                ('image', models.IntegerField(null=True, verbose_name='Изобржение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('model_type', models.CharField(max_length=255, verbose_name='Тип')),
                ('form_factor', models.CharField(max_length=255, verbose_name='Форм фактор')),
                ('data_interface', models.CharField(max_length=255, verbose_name='Интерфейс передачи данных')),
                ('read_speed', models.CharField(max_length=255, verbose_name='Скорость чтений')),
                ('write_speed', models.CharField(max_length=255, verbose_name='Скорость записи')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(null=True)),
                ('image', models.IntegerField(null=True, verbose_name='Изобржение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('core_number', models.CharField(max_length=255, verbose_name='Количество ядер')),
                ('clock_frequency', models.CharField(max_length=255, verbose_name='Тактовая частота')),
                ('cache', models.CharField(max_length=255, verbose_name='Кэш L3')),
                ('transistor_thickness', models.CharField(max_length=255, verbose_name='Толщина транзистора')),
                ('memory_support', models.CharField(max_length=255, verbose_name='Поддержка памяти')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(null=True)),
                ('image', models.IntegerField(null=True, verbose_name='Изобржение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('total_memory', models.CharField(max_length=255, verbose_name='Объем памяти')),
                ('memory_type', models.CharField(max_length=255, verbose_name='Тип памяти')),
                ('form_factor', models.CharField(max_length=255, verbose_name='Форм фактор')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('clock_frequency', models.CharField(max_length=255, verbose_name='Тактовая частота')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(null=True)),
                ('image', models.IntegerField(null=True, verbose_name='Изобржение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('gpu_manufacturer', models.CharField(max_length=255, verbose_name='Производитель графического процессора')),
                ('graphics_processor', models.CharField(max_length=255, verbose_name='Графический процессор')),
                ('gpu_frequency', models.CharField(max_length=255, verbose_name='Частота графического процессора')),
                ('video_memory', models.CharField(max_length=255, verbose_name='Видеопамять')),
                ('supply_power', models.CharField(max_length=255, verbose_name='Мощность блока питания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ram',
            name='pc',
        ),
        migrations.DeleteModel(
            name='Video_cards',
        ),
        migrations.RemoveField(
            model_name='motherboards',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='motherboards',
            name='name_of_motherboard',
        ),
        migrations.AddField(
            model_name='motherboards',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='motherboards',
            name='chipset',
            field=models.CharField(default='', max_length=255, verbose_name='Чипсет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboards',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='motherboards',
            name='form_factor',
            field=models.CharField(default='', max_length=255, verbose_name='Форм фактор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboards',
            name='image',
            field=models.IntegerField(null=True, verbose_name='Изобржение'),
        ),
        migrations.AddField(
            model_name='motherboards',
            name='memory_slots',
            field=models.CharField(default='', max_length=255, verbose_name='Количество слотов памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboards',
            name='memory_type',
            field=models.CharField(default='', max_length=255, verbose_name='Тип памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboards',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='motherboards',
            name='processor_support',
            field=models.CharField(default='', max_length=255, verbose_name='Поддержка процессоров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboards',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='motherboards',
            name='socket',
            field=models.CharField(default='', max_length=255, verbose_name='Сокет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboards',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.DeleteModel(
            name='Pc',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
    ]
