# Generated by Django 3.1.4 on 2021-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210202_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('age', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Computers',
            new_name='Computer',
        ),
        migrations.RenameModel(
            old_name='HardDrives',
            new_name='HardDrive',
        ),
        migrations.RenameModel(
            old_name='Motherboards',
            new_name='Motherboard',
        ),
        migrations.RenameModel(
            old_name='Processors',
            new_name='Processor',
        ),
        migrations.RenameModel(
            old_name='Rams',
            new_name='Ram',
        ),
        migrations.RenameModel(
            old_name='VideoCards',
            new_name='VideoCard',
        ),
    ]
