# Generated by Django 3.1.4 on 2021-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210204_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобржение'),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобржение'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобржение'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобржение'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобржение'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изобржение'),
        ),
    ]
