# Generated by Django 3.1.4 on 2021-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonynous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
