# Generated by Django 3.1.4 on 2021-02-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210216_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='finale_price',
            new_name='final_price',
        ),
    ]
