# Generated by Django 3.1.4 on 2021-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210216_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='credit_card_number',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
